spring.application.name: employee-api
server.port: 8111
employee.api.url: http://localhost:8112/api/v1/employee

spring:
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false


# Configuration for circuit breaker
resilience4j:
  circuitbreaker:
    instances:
      employeeService:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
# configuration for retry mechanism
  retry:
    instances:
      employeeService:
        maxAttempts: 3
        waitDuration: 2s




